### ISSUE TITLE
Support for more complex BOFs

### ISSUE THREAD

**Issue by Invoke-Mimikatz** [frkngksl/NiCOFF#1]
Hey,

Great tool! Thanks for sharing.

I have been testing running various BOFs in this tool and noticed simple BOFs like the TrustedSec situational awareness BOFs work just fine, but some BOFs have issues running in this loader, such as Helpsystems' Nanodump will crash the loader during execution.

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/57604669/182009028-84dd5acd-8992-4e86-a21a-f88219d256d2.png">

Wondering if you've tested more complex BOFs like this before, and if you've encountered similar crashes.

**Comment by frkngksl** [comment]
Hi! Thanks for your comment. After seeing your screenshot, I am suspecting from the BeaconPrintf function. Can you give me the exact arguments that you tried? Also, did you try this bof with the Trustedsec's COFFLoader?

**Comment by Invoke-Mimikatz** [comment]
Here's Nanodump in the TrustedSec COFFLoader:

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/57604669/182042981-548d2499-15a2-4227-a95b-b41e7d7ee238.png">

Of note, there is more output in the TS COFFLoader. Both NiCOFF and COFFLoader create a minidump, but the TS COFFLoader does not crash during execution of Nanodump.

The arguments I used for Nanodump:
```
$ ./bof_pack.py iziiiiiiiiziiiz 764 test2.dmp 1 1 0 0 0 0 0 0 "" 0 0 0 ""
764 test2.dmp 1 1 0 0 0 0 0 0  0 0 0  ("iziiiiiiiiziiiz")
-hex-> 48000000fc0200000a00000074657374322e646d7000010000000100000000000000000000000000000000000000000000000000000001000000000000000000000000000000000100000000
```
The `bof_pack()` argument signature was taken from the Nandump CNA script: https://github.com/helpsystems/nanodump/blob/main/NanoDump.cna#L405

**Comment by frkngksl** [comment]
I guess @JoernHe fixed the issue with the PR, I will merge this after verifying it. You can also say the PR fixed the issue. Thank you both so much !

**Comment by Invoke-Mimikatz** [comment]
I got a chance to test PR #2 and it fixes the issue. Thank you @JoernHe! 🥳
